name: DevOps_Build_Pipeline
inputs:
  project-path:
    description: "Path to the .csproj file"
    required: true
  build-config:
    description: "Build configuration (e.g., Release)"
    required: false
    default: "Release"

  artifact-name:
    description: "Name of the artifact to publish"
    required: true
  path:
    description: "Path to the artifact directory"
    required: true
runs:
  using: composite
  steps:
  - uses: "./.github/actions/build_dotnetrestore"
    with:
        project-path: ${{ inputs.project-path }}
  - uses: "./.github/actions/build_dotnetbuild"
    with:
        project-path: ${{ inputs.project-path }}
        build-config: ${{ inputs.build-config }}
  - uses: "./.github/actions/build_dotnetpublish"
    with:
        project-path: ${{ inputs.project-path }}
  - uses: "./.github/actions/build_publishartifacts"
    with:
        name: ${{ inputs.artifact-name }}
        path: ${{ runner.temp }}/artifact

